apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheusservice }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.prometheusApplicationName}}
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
